comparisons = [
    (0.000001, "a single clock cycle in a computer processor"),
    (0.00001, "a single pixel shift on a screen"),
    (0.0001, "the time it takes for light to travel 30 cm in a vacuum"),
    (0.001, "a blink of an eye"),
    (0.002, "the time it takes to press a button on a keyboard"),
    (0.005, "a quick tap on your phone screen"),
    (0.01, "the time it takes to blink once"),
    (0.015, "a quick twitch of your finger"),
    (0.02, "the time it takes to snap your fingers"),
    (0.025, "the time it takes to open a single app on your phone"),
    (0.03, "a quick breath"),
    (0.04, "a quick thought"),
    (0.05, "a tiny cough"),
    (0.06, "the time it takes for a hummingbird's wings to flap once"),
    (0.07, "the time it takes for a lightbulb to switch on fully"),
    (0.1, "flipping a light switch"),
    (0.15, "the time it takes to type a single letter on a keyboard"),
    (0.2, "the blink of an eye"),
    (0.25, "the time it takes to swipe on your phone screen"),
    (0.3, "a quick glance around the room"),
    (0.5, "pouring a cup of coffee"),
    (0.75, "the time it takes for a fast car to travel 10 meters"),
    (1, "grabbing a snack"),
    (2, "taking a short walk to the fridge"),
    (3, "a quick conversation"),
    (5, "watching a short video"),
    (7, "taking a deep breath"),
    (10, "boiling water for tea"),
    (15, "checking your watch"),
    (30, "listening to a song"),
    (60, "making a phone call"),
    (120, "watching a YouTube video"),
    (180, "cooking instant noodles"),
    (300, "reading a short article online"),
    (600, "taking a quick shower")
]

def get_comparison(elapsed_time: float | int):
    return min(comparisons, key=lambda x: abs(x[0] - elapsed_time))
